version: '3.8'

services:
  rabbitmq:
    restart: on-failure
    image: bitnamilegacy/rabbitmq:3.11.15
    expose:
      - "15672"
      - "5672"
      - "5671"
      - "15675"
      - "1883"
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5671:5671"
      - "15675:15675"
      - "1883:1883"
    networks:
      integration-net:
        aliases:
          - rabbitmq
    environment:
      - RABBITMQ_USERNAME=user
      - RABBITMQ_PASSWORD=bitnami
      - RABBITMQ_VHOST=/
      - RABBITMQ_PLUGINS=rabbitmq_management,rabbitmq_management_agent,rabbitmq_web_dispatch,rabbitmq_auth_mechanism_ssl

    volumes:
      - "./rabbitmq_conf/custom.conf:/bitnami/rabbitmq/conf/custom.conf"
      - "./rabbitmq_conf/server:/bitnami/tls-test"
      - rmq_data:/bitnami/rabbitmq

networks:
  integration-net:
    driver: bridge

volumes:
  rmq_data:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=35840m"
